<?php

/**
 * This is the model base class for the table "scenes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Scenes".
 *
 * Columns in table "scenes" available as properties of the model,
 * followed by relations of table "scenes" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $location_id
 *
 * @property Locations $location
 */
abstract class BaseScenes extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'scenes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Scenes|Scenes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('location_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('name, location_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, location_id', 'safe', 'on'=>'search'),
			array('id, name, location_id', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
			'location' => array(self::BELONGS_TO, 'Locations', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'location_id' => null,
			'location' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('location_id', $this->location_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}