<?php

/**
 * This is the model base class for the table "progresses".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Progresses".
 *
 * Columns in table "progresses" available as properties of the model,
 * followed by relations of table "progresses" available as properties of the model.
 *
 * @property integer $id
 * @property string $showload
 * @property string $showwait
 * @property string $showreloads
 * @property string $bar_origin
 * @property string $bar_width
 * @property string $bar_height
 * @property integer $bar_offsetx
 * @property string $bar_offsety
 * @property string $bar_style
 * @property string $bar_backcolor
 * @property string $bar_loadcolor
 * @property string $bar_decodecolor
 * @property string $bar_bordercolor
 * @property string $bar_borderwidth
 * @property string $bar_glowcolor
 * @property integer $bar_glowwidth
 * @property string $loopings_color
 * @property integer $loopings_points
 * @property integer $loopings_size
 * @property integer $loopings_bigpoint
 * @property integer $loopings_smallpoint
 * @property string $loopings_glowcolor
 * @property integer $loopings_glowwidth
 * @property double $loopings_xpos
 * @property double $loopings_ypos
 *
 * @property Projects[] $projects
 */
abstract class BaseProgresses extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'progresses';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Progresses|Progresses', $n);
	}

	public static function representingColumn() {
		return 'showload';
	}

	public function rules() {
		return array(
			array('bar_offsetx, bar_glowwidth, loopings_points, loopings_size, loopings_bigpoint, loopings_smallpoint, loopings_glowwidth', 'numerical', 'integerOnly'=>true),
			array('loopings_xpos, loopings_ypos', 'numerical'),
			array('showload', 'length', 'max'=>4),
			array('showwait', 'length', 'max'=>8),
			array('showreloads', 'length', 'max'=>5),
			array('bar_origin', 'length', 'max'=>11),
			array('bar_width, bar_height, bar_offsety, bar_backcolor, bar_loadcolor, bar_decodecolor, bar_bordercolor, bar_borderwidth, bar_glowcolor, loopings_color, loopings_glowcolor', 'length', 'max'=>255),
			array('bar_style', 'length', 'max'=>6),
			array('showload, showwait, showreloads, bar_origin, bar_width, bar_height, bar_offsetx, bar_offsety, bar_style, bar_backcolor, bar_loadcolor, bar_decodecolor, bar_bordercolor, bar_borderwidth, bar_glowcolor, bar_glowwidth, loopings_color, loopings_points, loopings_size, loopings_bigpoint, loopings_smallpoint, loopings_glowcolor, loopings_glowwidth, loopings_xpos, loopings_ypos', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, showload, showwait, showreloads, bar_origin, bar_width, bar_height, bar_offsetx, bar_offsety, bar_style, bar_backcolor, bar_loadcolor, bar_decodecolor, bar_bordercolor, bar_borderwidth, bar_glowcolor, bar_glowwidth, loopings_color, loopings_points, loopings_size, loopings_bigpoint, loopings_smallpoint, loopings_glowcolor, loopings_glowwidth, loopings_xpos, loopings_ypos', 'safe', 'on'=>'search'),
			array('id, showload, showwait, showreloads, bar_origin, bar_width, bar_height, bar_offsetx, bar_offsety, bar_style, bar_backcolor, bar_loadcolor, bar_decodecolor, bar_bordercolor, bar_borderwidth, bar_glowcolor, bar_glowwidth, loopings_color, loopings_points, loopings_size, loopings_bigpoint, loopings_smallpoint, loopings_glowcolor, loopings_glowwidth, loopings_xpos, loopings_ypos', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
			'projects' => array(self::HAS_MANY, 'Projects', 'progress_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'showload' => Yii::t('app', 'Showload'),
			'showwait' => Yii::t('app', 'Showwait'),
			'showreloads' => Yii::t('app', 'Showreloads'),
			'bar_origin' => Yii::t('app', 'Bar Origin'),
			'bar_width' => Yii::t('app', 'Bar Width'),
			'bar_height' => Yii::t('app', 'Bar Height'),
			'bar_offsetx' => Yii::t('app', 'Bar Offsetx'),
			'bar_offsety' => Yii::t('app', 'Bar Offsety'),
			'bar_style' => Yii::t('app', 'Bar Style'),
			'bar_backcolor' => Yii::t('app', 'Bar Backcolor'),
			'bar_loadcolor' => Yii::t('app', 'Bar Loadcolor'),
			'bar_decodecolor' => Yii::t('app', 'Bar Decodecolor'),
			'bar_bordercolor' => Yii::t('app', 'Bar Bordercolor'),
			'bar_borderwidth' => Yii::t('app', 'Bar Borderwidth'),
			'bar_glowcolor' => Yii::t('app', 'Bar Glowcolor'),
			'bar_glowwidth' => Yii::t('app', 'Bar Glowwidth'),
			'loopings_color' => Yii::t('app', 'Loopings Color'),
			'loopings_points' => Yii::t('app', 'Loopings Points'),
			'loopings_size' => Yii::t('app', 'Loopings Size'),
			'loopings_bigpoint' => Yii::t('app', 'Loopings Bigpoint'),
			'loopings_smallpoint' => Yii::t('app', 'Loopings Smallpoint'),
			'loopings_glowcolor' => Yii::t('app', 'Loopings Glowcolor'),
			'loopings_glowwidth' => Yii::t('app', 'Loopings Glowwidth'),
			'loopings_xpos' => Yii::t('app', 'Loopings Xpos'),
			'loopings_ypos' => Yii::t('app', 'Loopings Ypos'),
			'projects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('showload', $this->showload, true);
		$criteria->compare('showwait', $this->showwait, true);
		$criteria->compare('showreloads', $this->showreloads, true);
		$criteria->compare('bar_origin', $this->bar_origin, true);
		$criteria->compare('bar_width', $this->bar_width, true);
		$criteria->compare('bar_height', $this->bar_height, true);
		$criteria->compare('bar_offsetx', $this->bar_offsetx);
		$criteria->compare('bar_offsety', $this->bar_offsety, true);
		$criteria->compare('bar_style', $this->bar_style, true);
		$criteria->compare('bar_backcolor', $this->bar_backcolor, true);
		$criteria->compare('bar_loadcolor', $this->bar_loadcolor, true);
		$criteria->compare('bar_decodecolor', $this->bar_decodecolor, true);
		$criteria->compare('bar_bordercolor', $this->bar_bordercolor, true);
		$criteria->compare('bar_borderwidth', $this->bar_borderwidth, true);
		$criteria->compare('bar_glowcolor', $this->bar_glowcolor, true);
		$criteria->compare('bar_glowwidth', $this->bar_glowwidth);
		$criteria->compare('loopings_color', $this->loopings_color, true);
		$criteria->compare('loopings_points', $this->loopings_points);
		$criteria->compare('loopings_size', $this->loopings_size);
		$criteria->compare('loopings_bigpoint', $this->loopings_bigpoint);
		$criteria->compare('loopings_smallpoint', $this->loopings_smallpoint);
		$criteria->compare('loopings_glowcolor', $this->loopings_glowcolor, true);
		$criteria->compare('loopings_glowwidth', $this->loopings_glowwidth);
		$criteria->compare('loopings_xpos', $this->loopings_xpos);
		$criteria->compare('loopings_ypos', $this->loopings_ypos);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}