<?php

/**
 * This is the model base class for the table "memories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Memories".
 *
 * Columns in table "memories" available as properties of the model,
 * followed by relations of table "memories" available as properties of the model.
 *
 * @property integer $id
 * @property integer $maxmem
 *
 * @property Projects[] $projects
 */
abstract class BaseMemories extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'memories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Memories|Memories', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('maxmem', 'numerical', 'integerOnly'=>true),
			array('maxmem', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, maxmem', 'safe', 'on'=>'search'),
			array('id, maxmem', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
			'projects' => array(self::HAS_MANY, 'Projects', 'memory_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'maxmem' => Yii::t('app', 'Maxmem'),
			'projects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('maxmem', $this->maxmem);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}