<?php

/**
 * This is the model base class for the table "settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Settings".
 *
 * Columns in table "settings" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $image_id
 * @property integer $preview_id
 * @property integer $display_id
 * @property integer $view_id
 *
 */
abstract class BaseSettings extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Settings|Settings', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('image_id, preview_id, display_id, view_id', 'numerical', 'integerOnly'=>true),
			array('image_id, preview_id, display_id, view_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, image_id, preview_id, display_id, view_id', 'safe', 'on'=>'search'),
			array('id, image_id, preview_id, display_id, view_id', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'image_id' => Yii::t('app', 'Image'),
			'preview_id' => Yii::t('app', 'Preview'),
			'display_id' => Yii::t('app', 'Display'),
			'view_id' => Yii::t('app', 'View'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('image_id', $this->image_id);
		$criteria->compare('preview_id', $this->preview_id);
		$criteria->compare('display_id', $this->display_id);
		$criteria->compare('view_id', $this->view_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}