<script type="text/javascript">
<!-- Init -->
/*
$(document).ready(function(){
	$(function() {
		//range

		var project_slider_array = ["#display_Tessmode_slider","#control_Keybfovchange_slider",
		"#display_Details_slider", "#display_Stilltime_slider", "#display_Fps_slider", "#network_Decodequeues_slider", "#network_Downloadqueues_slider",
		"#network_Retrycount_slider", "#network_Cachesize_slider", "#network_Maxmem_slider", "#control_Mouseaccelerate_slider", "#control_Mousespeed_slider",
		"#control_Mousefriction_slider", "#control_Mousefovchange_slider", "#control_Keybspeed_slider", "#control_Keybfriction_slider", "#control_Fovspeed_slider",
		"#control_Fovfriction_slider", "#control_Cursorsize_slider", "#control_Headswing_slider", "#control_Touchfriction_slider", "#autorotate_Waittime_slider",
		"#autorotate_Speed_slider", "#autorotate_Accel_slider"
		];
		
		$(project_slider_array.join(",")).bind("slide", function(event, ui) {
			var slider_div_id = $(this).attr('id');
			var amount_div_id = "#" + slider_div_id.replace(/_slider/, "") + "_amount"; 
			$(amount_div_id).val(ui.value);
			
			var property = slider_div_id.split("_")[0] + "." + slider_div_id.split("_")[1];
			setKrpanoProperty(property, ui.value);
			
		});	

		//on/off slider
		$("#display_Flash10_slider").slider({min: 0, max: 1, value: 1, step: 1,		
			slide: function(event, ui) {
				var sliderid = $(this).attr('id');
				var amountid = "#" + sliderid.replace(/_slider/, "") + "_amount"; 
				var property = sliderid.split("_")[0] + "." + sliderid.split("_")[1];
				if(ui.value == 1)
				{
					$(amountid).val("on");
				}
				else
				{
					$(amountid).val("off");
				}
				setKrpanoProperty(property, ui.value);
			}
		});
		$("#display_Showpolys_slider, #network_Caching_slider, #control_Keybinvert_slider, #control_Zoomtocursor_slider, #control_Zoomoutcursor_slider, #control_Trackpadzoom_slider, #autorotate_Enabled_slider").slider({min: 0, max: 1, value: 1, step: 1,		
			slide: function(event, ui) {
				var sliderid = $(this).attr('id');
				var amountid = "#" + sliderid.replace(/_slider/, "") + "_amount"; 
				var property = sliderid.split("_")[0] + "." + sliderid.split("_")[1];
				if(ui.value == 1)
				{
					$(amountid).val("true");
				}
				else
				{
					$(amountid).val("false");
				}
				setKrpanoProperty(property, ui.value);
			}
		});

		$("#autorotate_Horizon_slider").slider({min: -90.1, max: 90.0, value: -90.1, step: 0.1,		
			slide: function(event, ui) {
				var sliderid = $(this).attr('id');
				var amountid = "#" + sliderid.replace(/_slider/, "") + "_amount"; 
				var property = sliderid.split("_")[0] + "." + sliderid.split("_")[1];

				if(ui.value == -90.1){
					$(amountid).val("off");
				}else{
					$(amountid).val(ui.value);
				}
				setKrpanoProperty(property, ui.value);
			}
		});	
		//dropdown option boxes
		var project_option_array = ["#control_Mousetype_amount","#display_Movequality_amount","#display_Stillquality_amount"];
		$(project_option_array.join(",")).change(function() {
			var id = $(this).attr("id");
			var value = $("#" + id + " option:selected").val();
			
			var property = id.split("_")[0] + "." + id.split("_")[1];
			setKrpanoProperty(property, value);
		});
	});
});
function setKrpanoProperty(property,value)
{
	var property = property.toLowerCase();
	krpano().set(property,value);
	krpano().call("trace('set("+property+","+value+")')");
	//updateobject() required for some properties.
	if(property == "display.details" || property == "display.tessmode" || property == "image.hfov" || property == "image.vfov" || property == "image.voffset"){
		krpano().call("trace('updateobject()')");
		krpano().call("updateobject(true,true)");
	}
	
}*/
<!-- initial slider values, generated by PHP -->
$(document).ready(function(){
	$(function(){
<? 
foreach($krpano_attri as $attri_name => $arr){
	foreach ($arr as $k => $v) {
		if($k == "Movequality" || $k == "Stillquality" || $k == "Mousetype" || $k == "Usercontrol") {
			/*dropdownbox */
			echo  "	/* Dropdownbox: $attri_name.$k */ \n";
			echo "	\$(\"#".$attri_name."_".$k."_amount\").val(\"$v\");\n";	
			echo "\n ";
		}
		else {
			/*sliders */
			echo  "	/* sliders: $attri_name.$k */ \n";
			echo "	\$(\"#".$attri_name."_".$k."_slider\").slider(\"value\", $v);\n";
			
			if($k == "Flash10" || $k == "Showpolys" || $k == "Keybinvert" || $k == "Zoomtocursor" || $k == "Zoomoutcursor" || $k == "Trackpadzoom" || $k == "Enabled")
			{
				if($k == "Flash10"){
					$value = $v == "1" ? "on" : "off";
				}
				else{
					$value = $v == "1" ? "true" : "false";
				}
				echo "	\$(\"#".$attri_name."_".$k."_amount\").val(\"$value\");\n";
			}
			else {
				echo "	\$(\"#".$attri_name."_".$k."_amount\").val(\"$v\");\n";
			}
			echo "\n ";
		}
	}
}
?>
	});
	function loadGlobal(){
	<? 
	foreach($krpano_attri as $attri_name => $arr){
		foreach ($arr as $k => $v) {
			echo "	krpano().set(\"".$attri_name.".".$k."\",\"".$v."\");\n";
		}
	}
	?>
	}
	$(function(){
		var advanced_mode = $('#project_Showadvanced_amount').attr('checked')? 'table-row' : 'none';
		$('#display_Tessmode_amount').closest('tr').css('display',advanced_mode);
		$('#display_Shoiwpolys_amount').closest('tr').css('display',advanced_mode);
		$('#display_Stilltime_amount').closest('tr').css('display',advanced_mode);
		$('#network_Retrycount_amount').closest('tr').css('display',advanced_mode);
		$('#network_Caching_amount').closest('tr').css('display',advanced_mode);
		$('#network_Cachesize_amount').closest('tr').css('display',advanced_mode);
		$('#control_Usercontrol_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keybaccelerate_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keybspeed_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keybfriction_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keybfovchange_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keybinvert_amount').closest('tr').css('display',advanced_mode);
		$('#control_Movetocursor_amount').closest('tr').css('display',advanced_mode);
		$('#control_Cursorsize_amount').closest('tr').css('display',advanced_mode);
		$('#control_Headswing_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesleft_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesright_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesup_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesdown_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesin_amount').closest('tr').css('display',advanced_mode);
		$('#control_Keycodesout_amount').closest('tr').css('display',advanced_mode);
		$('#autorotate_Accel_amount').closest('tr').css('display',advanced_mode);
		$('#autorotate_Horizon_amount').closest('tr').css('display',advanced_mode);
		$('#autorotate_Tofov_amount').closest('tr').css('display',advanced_mode);
	});
	$(function(){
		$('#settings_Project_submit').click(function() {
			var answer = confirm("Are you sure you want to copy that projects settings? It will wipe the current settings!");
			return answer;
		});
	});
	/* zoom in/out dashboard icons */
	$("ul.dashboard li").hover(function() {
	$(this).css({'z-index' : '100'}); /*Add a higher z-index value so this image stays on top*/ 
	$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
		.animate({
			marginTop: '-80px', /* The next 4 lines will vertically align this image */ 
			marginLeft: '-80px',
			top: '50%',
			left: '50%',
			width: '100px', /* Set new width */
			height: '100px', /* Set new height */
			padding: '20px'
		}, 400); 

	} , function() {
	$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
	$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
		.animate({
			marginTop: '0', /* Set alignment back to default */
			marginLeft: '0',
			top: '0',
			left: '0',
			width: '70px', /* Set width back to default */
			height: '70px', /* Set height back to default */
			padding: '0px'
		}, 400);
	});

});
function updateProject()
{
	var postData = {
	<? 
	foreach($krpano_attri as $property_name => $property_array){
		foreach ($property_array as $attribute => $value) {
			echo "		".$property_name."_".$attribute."_amount:		\$(\"#".$property_name."_".$attribute."_amount\").val(), \n";
		}
	}
	?>
		ajax: '1'		
	};	
	$.ajax({
		url: "<?php echo site_url('projects/updateProject'); ?>",
		type: 'POST',
		data: postData,
		dataType: 'html',
		success: function(data) {				
				if(data == 1)
				{
					$("#save_succes_message_box").css("display","inline");
					$("#save_error_message_box").css("display","none");
					$(".save_message").html("project succesfully saved");	
				}
				else
				{
					$("#save_succes_message_box").css("display","none");
					$("#save_error_message_box").css("display","inline");
					$(".save_message").html("problem occured while saving to database");
				}
		}
	}); 	
}

</script>