<?php
$this->breadcrumbs=array(
	'Hotspots'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Hotspots', 'url'=>array('index')),
	array('label'=>'Create Hotspots', 'url'=>array('create')),
	array('label'=>'Update Hotspots', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Hotspots', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Hotspots', 'url'=>array('admin')),
);
?>

<h1>View Hotspots #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'LocationId',
		'name',
		'alturl',
		'keep',
		'devices',
		'visible',
		'enabled',
		'scale9grid',
		'zorder',
		'capture',
		'children',
		'preload',
		'blendmode',
		'edge',
		'ox',
		'oy',
		'zoom',
		'distorted',
		'rx',
		'ry',
		'rz',
		'inverserotation',
		'flying',
		'width',
		'height',
		'scale',
		'altscale',
		'rotate',
		'smoothing',
		'accuracy',
		'alpha',
		'usecontentsize',
		'type',
		'meta',
		'url',
		'ath',
		'atv',
		'onover',
		'onout',
		'onclick',
		'crop',
		'onovercrop',
		'ondowncrop',
		'scalechildren',
		'mask',
		'effect',
		'onhover',
		'ondown',
		'onup',
		'onloaded',
		'altonloaded',
		'handcursor',
		'style',
		'effects',
	),
)); ?>
