<?php

/**
 * This is the model base class for the table "maps".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Maps".
 *
 * Columns in table "maps" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $project_id
 * @property string $path
 * @property string $type
 *
 */
abstract class BaseMaps extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'maps';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Maps|Maps', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('project_id', 'numerical', 'integerOnly'=>true),
			array('path', 'length', 'max'=>150),
			array('type', 'length', 'max'=>50),
			array('project_id, path, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, project_id, path, type', 'safe', 'on'=>'search'),
			array('id, project_id, path, type', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'project_id' => Yii::t('app', 'Project'),
			'path' => Yii::t('app', 'Path'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}