<?php

/**
 * This is the model base class for the table "scenes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Scenes".
 *
 * Columns in table "scenes" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $Name
 * @property integer $location_id
 *
 */
abstract class BaseScenes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'scenes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Scenes|Scenes', $n);
	}

	public static function representingColumn() {
		return 'Name';
	}

	public function rules() {
		return array(
			array('location_id', 'numerical', 'integerOnly'=>true),
			array('Name', 'length', 'max'=>50),
			array('Name, location_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Name, location_id', 'safe', 'on'=>'search'),
			array('id, Name, location_id', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'Name' => Yii::t('app', 'Name'),
			'location_id' => Yii::t('app', 'Location'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Name', $this->Name, true);
		$criteria->compare('location_id', $this->location_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}