<?php

/**
 * This is the model base class for the table "krpano_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KrpanoCategories".
 *
 * Columns in table "krpano_categories" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $name
 *
 */
abstract class BaseKrpanoCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'krpano_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'KrpanoCategories|KrpanoCategories', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('name', 'numerical', 'integerOnly'=>true),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name', 'safe', 'on'=>'search'),
			array('id, name', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}