<?php

/**
 * This is the model base class for the table "settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Settings".
 *
 * Columns in table "settings" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $ImageId
 * @property integer $PreviewId
 * @property integer $DisplayId
 * @property integer $ViewId
 *
 */
abstract class BaseSettings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Settings|Settings', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('ImageId, PreviewId, DisplayId, ViewId', 'numerical', 'integerOnly'=>true),
			array('ImageId, PreviewId, DisplayId, ViewId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ImageId, PreviewId, DisplayId, ViewId', 'safe', 'on'=>'search'),
			array('id, ImageId, PreviewId, DisplayId, ViewId', 'safe', 'on'=>'api'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ImageId' => Yii::t('app', 'Image'),
			'PreviewId' => Yii::t('app', 'Preview'),
			'DisplayId' => Yii::t('app', 'Display'),
			'ViewId' => Yii::t('app', 'View'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ImageId', $this->ImageId);
		$criteria->compare('PreviewId', $this->PreviewId);
		$criteria->compare('DisplayId', $this->DisplayId);
		$criteria->compare('ViewId', $this->ViewId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}