
<div class="accordion" >
	<h3><a href="#">Main page</a></h3>
	<div>
		<div id="Global"> <!-- BEGIN GLOBAL TAB -->
			<table cellspacing="0" class="tableinformation corners_bottom">
				<thead>
					<tr>
						<th class="header_attribute">Attribute</th>
						<th class="value_attribute">Value</th>
					</tr>
				</thead>
				<tbody>
					<tr> <!-- Name -->
						<td class="attribute">
							<h5>Name
								<div class="tooltip">
									Name of the hotspot. This is autogenerated.
								</div>
							</h5>
						</td>
						<td>
							<span id="hotspot_Name_amount"></span>
						</td>
					</tr>
					<tr> <!-- Body background image -->
						<td class="attribute">
							<h5>Background
								<div class="tooltip">
									Name of the hotspot. This is autogenerated.
								</div>
							</h5>
						</td>
						<td>
							<ul id="background_list">
								<li><a href="#" id="background_1">1</a></li>
								<li><a href="#" id="background_2">2</a></li>
								<li><a href="#" id="background_3">3</a></li>
								<li><a href="#" id="background_4">4</a></li>
								<li><a href="#" id="background_5">5</a></li>
							</ul>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<h3><a href="#">Skin & Icons</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
	<h3><a href="#">Header</a></h3>
	<div>
		<table cellspacing="0" class="tableinformation corners_bottom">
			<thead>
				<tr>
					<th class="header_attribute">Attribute</th>
					<th class="value_attribute">Value</th>
				</tr>
			</thead>
			<tbody>
				<tr> <!-- Background color -->
					<td class="attribute">
						<h5>Background
							<div class="tooltip">
								The backgroundcolor of the header
							</div>
						</h5>
					</td>
					<td>
						<input id="theme_Headerbackground_amount" type="color" value="#ff0667" data-hex="true" class="corners" />
					</td>
				</tr>
				<tr> <!-- Opacity of the header -->
					<td class="attribute">
						<h5>Transparency
							<div class="tooltip">
								The transparency of the header
							</div>
						</h5>
					</td>
					<td>
						<div id="theme_Headeropacity_slider"></div>
						<input type="text" name="theme_Headeropacity_amount" id="theme_Headeropacity_amount" class="xxsmall_input corners" />
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<h3><a href="#">Footer</a></h3>
	<div>
		<table cellspacing="0" class="tableinformation corners_bottom">
			<thead>
				<tr>
					<th id="Footer_attribute">Attribute</th>
					<th class="value_attribute">Value</th>
				</tr>
			</thead>
			<tbody>
				<tr> <!-- Background color -->
					<td class="attribute">
						<h5>Background
							<div class="tooltip">
								The backgroundcolor of the Footer
							</div>
						</h5>
					</td>
					<td>
						<input id="theme_Footerbackground_amount" type="color" value="#ff0667" data-hex="true" class="corners" />
					</td>
				</tr>
				<tr> <!-- Opacity of the Footer -->
					<td class="attribute">
						<h5>Transparency
							<div class="tooltip">
								The transparency of the Footer
							</div>
						</h5>
					</td>
					<td>
						<div id="theme_Footeropacity_slider"></div>
						<input type="text" name="theme_Footeropacity_amount" id="theme_Footeropacity_amount" class="xxsmall_input corners" />
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<h3><a href="#">Tooltips</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
	<h3><a href="#">Interface</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
</div>